GET http://localhost:8080/api/games

###

GET http://localhost:8080/api/genres

###

GET http://localhost:8080/api/streamers

###

GET http://localhost:8080/api/streamers/15

###

GET http://localhost:8080/api/streamers/15/games

###

DELETE http://localhost:8080/api/games/13

###

DELETE http://localhost:8080/api/genres/1

###

GET http://localhost:8080/api/genres/20

###

GET http://localhost:8080/api/genres/1/games

###

GET http://localhost:8080/api/games/69

###

GET http://localhost:8080/api/games/9/streamers

###

GET http://localhost:8080/api/games/35/streamers

###

POST http://localhost:8080/api/genres
Content-Type: application/json

{
  "name": "genre1",
  "description": "description description description"
}

###

PUT http://localhost:8080/api/genres/20
Content-Type: application/json

{
  "description": "genre 1 after update"
}

###

PUT http://localhost:8080/api/streamers/17
Content-Type: application/json

{
  "playedGames" : [
    "Hearthstone",
    "Among Us",
    "World of Warcraft"
  ]
}

###

DELETE http://localhost:8080/api/streamers/17

###

DELETE http://localhost:8080/api/genres/18